# Generated by Django 5.1.3 on 2024-11-06 18:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.UUIDField()),
                ('profile_id', models.UUIDField()),
                ('account_id', models.UUIDField()),
                ('data', models.JSONField()),
            ],
        ),
    ]
